### ISSUE TITLE
Faire fonctionner le filter weglot_language_code_replace avec le plugin Code Snippet

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#104]
Pour l'instant ce filter :

```add_filter( 'weglot_language_code_replace', 'custom_weglot_language_code_replace' );
function custom_weglot_language_code_replace( $replacements ) { 
	$replacements['tw'] = 'zh-HK';
	//$replacements['fr'] = 'fr_CA';
    return $replacements;
}
```

fonctionne en le mettaint dans wp-include mais pas avec le plugin codeSnippet

C'est à cause du fait qu'on appelle weglot_get_current_and_original_language trop tôt (avant plugin_loaded) via redirect-premium

**Comment by julien-jacob** [comment]
Fait dans le commit d051ed566ff3f1ba3cc513ffe093b75660f633b4 (https://github.com/weglot/translate-wordpress/commit/9ef9f2211cd7df418a5fa39a7df21e7a02d54bac)

Documentation et exemples de l'utilisation de ce hook disponible ici : https://app.gitbook.com/@weglot/s/doc/wordpress/use-cases/use-custom-language-code-url-lang-and-hreflang-attribute
