### ISSUE TITLE
Add RTL CSS property

### ISSUE THREAD

**Issue by julien-jacob** [weglot/translate-wordpress#110]
For RTL languages, add specific CSS properties 

Example : 
```
html[lang="ar"] body {
   direction: RTL!important;
   text-align: right!important;
}
```

**Comment by remyberda** [comment]
Il faudra faire des tests dessus + voir avec Christophe ce qu'il en pense

**Comment by remyberda** [comment]
On essaie de mettre ce CSS par défault sur les languages RTL
On laisse la possibilité au support de l'enlever au cas ou via un filtre

Ensuite il faut faire des tests sur plusieurs thèmes + plugins de slider

**Comment by remyberda** [comment]
On laisse comme c'est, on met déjà
`$GLOBALS['text_direction'] = 'rtl';` pour indiquer à WordPress la langue
