### ISSUE TITLE
Translation strings should not have dynamic values

### ISSUE THREAD

**Issue by joehoyle** [weglot/translate-wordpress#124]
Currently the strings around https://github.com/weglot/translate-wordpress/blob/dev/templates/admin/pages/tabs/appearance.php#L302 have the `admin_url` as part of the string, rather than a placeholder. Unless there's some serious magic going on to remove those that I don't know about, this will mean it's not possible to translate those strings as they will be different for each install.

**Comment by remyberda** [comment]
Done
