### ISSUE TITLE
Translate SVG URL for media translation

### ISSUE THREAD

**Issue by julien-jacob** [weglot/translate-wordpress#132]
Translate SVG URL for media translation

**Comment by remyberda** [comment]
J'ai regardé et on ne va pas traduire quand dans le HTML il y a directement le SVG.
Il faut uniquement vérifier que si on a un lien vers un fichier SVG il soit passé mais je pense que c'est le cas

Par exemple
`<img src="image.svg" />` => il faut qu'on passe umage.svg à l'API

Cordialement

**Comment by julien-jacob** [comment]
OK pour la version 3.1.8 
Commit : https://github.com/weglot/translate-wordpress/commit/908de7967c5a1253420f3f460eb766671d4be0ea
