### ISSUE TITLE
custom URL + permalinks issue

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#136]
Quand on a les permalinks sans "/" à la fin, par exemple
/%postname%

Et qu'on utilise des custom URLs, on a une 404

**Comment by julien-jacob** [comment]
Fix in next version : 3.1.9

**Comment by julien-jacob** [comment]
Done in 3.1.9 (https://github.com/weglot/translate-wordpress/releases/tag/3.1.9)
