### ISSUE TITLE
Custom links routing

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#137]
Je ne suis pas sur si c'est déjà réglé mais sur ce site:
https://luis-vives.es/fr/test-gratuits-diplomes-eso-et-bachillerato/

Quand tu es en FR, le lien vers l'anglais est pas bon, ça reprend le même custom link en FR

**Comment by julien-jacob** [comment]
Done in 3.1.9 (https://github.com/weglot/translate-wordpress/releases/tag/3.1.9)
