### ISSUE TITLE
Translated slug no 404/redirect

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#138]
Si on traduit un lien, par exemple
https://deportesurbanos.com/producto/mesa-ping-pong-exterior-sport/
https://deportesurbanos.com/fr/producto/table-ping-pong-fixe-exterieur-sport/

Le lien non traduit marche toujours :
https://deportesurbanos.com/fr/producto/mesa-ping-pong-exterior-sport/

Alors que ça ne devrait pas. Ca devrait faire 404 ou 301

**Comment by julien-jacob** [comment]
Done in 3.1.9
