### ISSUE TITLE
Language Code Url Position

### ISSUE THREAD

**Issue by mcl11** [weglot/translate-wordpress#141]
Hi There...

one question arose while using your Plugin within a WP Multisite system in connection with a subfolder structure.

1) **The main site:** www.mainsite.com
2) **A Subsite:** www.mainsite.com/subsite

Case 1) would be www.mainsite.com**/en/**
Case 2) would be www.mainsite.com/subsite**/en/**

Is it possible to change the structure that the language code always follows the main domain?
E. g. www.mainsite.com/**/en/**subsite

Thanks in Advance
Michael

**Comment by remyberda** [comment]
Hi Michael, 

Actually it's coded like this because if you have a multisite, it means the root URL is mainsite.com/subsite so the language subdomain should be mainsite.com/subsite otherwise you will get a 404

**Comment by mcl11** [comment]
Hi Rémy…

Ok, thanks for your answer…
All is working now… ;)

BR
Michael
