### ISSUE TITLE
Bug when path = path prefix

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#158]
Exemple ici : https://eden-boites.com/blog/blog/

**Comment by glx77** [comment]
Je suis sur le sujet, 
le soucis semble venir du bundle php weglot, quand on est en mode multisite on réccupère mal la vrai base url.

**Comment by glx77** [comment]
le soucis vient du bundle php, si on limite le preg replace à 1 seul occurence ici : weglot-php/src/Util/Url.php ligne 252

**Comment by remyberda** [comment]
resolved in 3.3.2
