### ISSUE TITLE
Add current language in menu switcher

### ISSUE THREAD

**Issue by Gmulti** [weglot/translate-wordpress#20]
Possibility to add a "current language" menu entry

**Comment by markhagemann** [comment]
By this do you mean instead of only being able to add a particular language (e.g. [weglot_menu_title-en] ) we would be able to add [weglot_switcher]? +1 if so.

**Comment by Gmulti** [comment]
New Weglot switcher available in version 2.4.0.
Available in the dev branch for the moment
