### ISSUE TITLE
Add new readme

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#91]
Ajouter le nouveau readme corrigé

**Comment by remyberda** [comment]
+ Mettre WordPress 5.3 dans le Tested Up to

**Comment by e-ernoult** [comment]
**Nouveau logo + banner**

J'ai suivi les instructions ici : https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/

![banner-772-500](https://user-images.githubusercontent.com/40290497/67494899-4f656980-f67a-11e9-9b87-23eb92933dad.png)
![banner-1544x500](https://user-images.githubusercontent.com/40290497/67494900-4ffe0000-f67a-11e9-85a9-7f6afd519375.png)
![icon-128x128](https://user-images.githubusercontent.com/40290497/67494901-4ffe0000-f67a-11e9-9b14-8f79bd2fb69f.png)
![icon-256x256](https://user-images.githubusercontent.com/40290497/67494903-4ffe0000-f67a-11e9-9cab-b16c5df9097f.png)

**Comment by remyberda** [comment]
@e-ernoult merci, on met ça dans la prochaine release. Pour les screenshots, on tu nous les donnes aussi ? On peut passer soit ça demain, sinon prochaine release, no rush ;)

**Comment by e-ernoult** [comment]
@remyberda Yes j'essaye de vous filer ça ce soir sinon ça sera dans la prochaine release

**Comment by remyberda** [comment]
Done en 3.1.3, il manque les screenshot
