### ISSUE TITLE
Check all Cache plugin : Autoptimize, Wp Fastest Cache

### ISSUE THREAD

**Issue by remyberda** [weglot/translate-wordpress#97]
Check all Cache plugin : Autoptimize, Wp Fastest Cache

**Comment by julien-jacob** [comment]
Autoptimize: OK -> /!\ Test with static cache 
Wp Fastest Cache: OK, static cache subfolder by language 
WP Optimize: NOT OK (Study override advanced-cache.php)

**Comment by julien-jacob** [comment]
WP Optimize: Compatibility adding in 3.1.4
